#In fact, a copy of dev compose yet with different .env and target
name: ${APP_NAME}

services:
  app:
    image: ${IMAGE_BASE:-default}-app:latest
    build:
      context: ./services/api
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      TZ: "Europe/Moscow"
      MODE: prod
      GIT_COMMIT: ${GIT_COMMIT}
    env_file:
      - .env
    networks:
      - project-network
    labels:
      loki.label.service_name: ${APP_NAME:-default}
      loki.label.service_type: api
      loki.label.env: prod


  celery_worker:
    image: ${IMAGE_BASE:-default}-celery_worker:latest
    build:
      context: ./services/api
      dockerfile: Dockerfile
      target: celery
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "celery", "-A", "app.infrastructure.dependencies:_celery", "status"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - ./services/api/app:/app/app
    environment:
      TZ: "Europe/Moscow"
      MODE: prod
      GIT_COMMIT: ${GIT_COMMIT}
      CELERY_WORKER_CONCURRENCY: 4
    env_file:
      - .env
    networks:
      - project-network
    command: celery -A app.infrastructure.dependencies:_celery worker --loglevel=info -P prefork -E
    labels:
      loki.label.service_name: ${APP_NAME:-default}
      loki.label.service_type: tasks
      loki.label.env: prod


  celery_beat:
    image: ${IMAGE_BASE:-default}-celery_beat:latest
    build:
      context: ./services/api
      dockerfile: Dockerfile
      target: celery
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "-f", "celery"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - ./services/api/app:/app/app
    environment:
      TZ: "Europe/Moscow"
      MODE: prod
      GIT_COMMIT: ${GIT_COMMIT}
    env_file:
      - .env
    networks:
      - project-network
    command: celery -A app.infrastructure.dependencies:_celery beat --loglevel=info
    labels:
      loki.label.service_name: ${APP_NAME:-default}
      loki.label.service_type: tasks
      loki.label.env: prod

  nginx:
    image: nginx:1.27.0
    restart: unless-stopped
    ports:
      - "127.0.0.1:9092:80"
    depends_on:
      - app
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./services/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf:ro
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - project-network
    labels:
      loki.label.service_name: ${APP_NAME:-default}
      loki.label.service_type: nginx
      loki.label.env: prod


  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=caching_sha2_password
    env_file: 
      - .env
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute='SELECT 1' $$MYSQL_DATABASE"]
      interval: 5s
      timeout: 5s
      retries: 40
      start_period: 30s
    networks:
      - project-network
    labels:
      loki.label.service_name: ${APP_NAME:-default}
      loki.label.service_type: db
      loki.label.env: prod


  redis:
    image: redis:latest
    restart: unless-stopped
    entrypoint: ["/bin/bash", "/usr/local/bin/redis-entrypoint.sh"]
    volumes:
      - redis:/data
      - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf.template:ro      
      - ./services/redis/redis-entrypoint.sh:/usr/local/bin/redis-entrypoint.sh:ro
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli","-a", "$$REDIS_PASS","ping"]
      interval: 10s
      retries: 3
      timeout: 3s
    networks:
      - project-network
    labels:
      loki.label.service_name: ${APP_NAME:-default}
      loki.label.service_type: cache
      loki.label.env: prod

###for UNIX systems
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/' #just for example
      - '--web.listen-address=:9000'
      - '--collector.hwmon'
    #volumes:
    #  - './:/host:ro,rslave'
    networks:
      - project-network
    restart: unless-stopped
    pid: host
    labels:
      loki.label.service_name: ${APP_NAME:-default}
      loki.label.service_type: node
      loki.label.env: prod

  k6:
    image: grafana/k6:latest
    env_file:
      - .env
    volumes:
      - ./services/k6/scripts:/scripts
    command: run /scripts/test_main.js
    networks:
      - project-network
    labels:
      loki.label.service_name: ${APP_NAME:-default}
      loki.label.service_type: load_tests
      loki.label.env: prod

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/promtail/config.yml:/etc/promtail/config.yml:ro
    command: 
      - '--config.file=/etc/promtail/config.yml'
    networks:
      - project-network
    labels:
      loki.label.service_name: ${APP_NAME:-default}
      loki.label.service_type: log_collector
      loki.label.env: prod


networks:
  project-network:
    name: ${APP_NAME}-net
    driver: bridge

volumes:
  db:
    name: ${APP_NAME}-db
  redis:
    name: ${APP_NAME}-redis
  prometheus-shared:
    name: ${APP_NAME}-prometheus-shared
