server:
  http_listen_port: 9000
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host.docker.internal:9010/loki/api/v1/push


scrape_configs:
  - job_name: docker_sd
    
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        
    relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: docker_sd

      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
        replacement: '$1'

      - source_labels: ['__address__']
        regex: __meta_docker_container_label_loki_label_(.+)
        action: labelmap
        replacement: $1
        
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
      - labeldrop:
          - attrs
      - labels:
          tag: