{
 "title": "UserAuthAPI",
 "description": "Reflects the state of the API from the technical viewpoint",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "TargetAPI", "label": "TargetAPI", "query": "user_auth" }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "description": "Requests per second",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api:exported_job:rps:1m{exported_job=\"${TargetAPI}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency P99  [1m]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api:exported_job:latency:p99:ms:1m{exported_job=\"${TargetAPI}\"}/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%5XX" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api:exported_job:http500:percent:1m{exported_job=\"${TargetAPI}\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Data IN: Bytes/s  [1m]",
   "type": "stat",
   "description": "Requests per second",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api:exported_job:requests_size:bytes:1m{exported_job=\"${TargetAPI}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS [1m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "api:exported_job:rps:1m{exported_job=\"${TargetAPI}\"}\r\n",
     "legendFormat": "{{http_target}} [{{http_method}}]"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api:exported_job:responses_ratio:percent:5m{exported_job=\"${TargetAPI}\", status_code=~'...'}\r\n",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Latency P95 [1m]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api:exported_job:latency:p95:ms:1m{exported_job=\"${TargetAPI}\"}/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data OUT: Bytes/s  [1m]",
   "type": "stat",
   "description": "Requests per second",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api:exported_job:response_size:bytes:1m{exported_job=\"${TargetAPI}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top-5 highest 5XX Err % endpoints [30s]",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(5,api:exported_job_target_method:500:percent:12h{exported_job=\"${TargetAPI}\"}) > 0",
     "legendFormat": "{{http_target}} [{{http_method}}]"
    }
   ]
  },
  {
   "title": "Responses by status code group [1h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "api:exported_job:responses_ratio:percent:5m{exported_job=\"${TargetAPI}\", status_code=~\"...\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Top-3 highest latency endpoints [30s]",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "topk(3,api:exported_job_target_method:latency:ms:30s{exported_job=\"${TargetAPI}\"}/1000) > 0",
     "legendFormat": "{{http_target}} [{{http_method}}]"
    }
   ]
  },
  {
   "title": "Requests latency distribution (buckets in ms) [1h]",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_milliseconds_bucket{exported_job=\"${TargetAPI}\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Top-3 highest latency P95 endpoints [30s]",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "topk(3,api:exported_job_target_method:latency:p95:ms:30s{exported_job=\"${TargetAPI}\"}/1000) > 0",
     "legendFormat": "{{http_target}} [{{http_method}}]"
    }
   ]
  },
  {
   "title": "Service logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_type=~\"api\"}"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "filters": [
      {
       "id": "390c2612",
       "isCustomValue": false,
       "operator": "=",
       "scope": "intrinsic",
       "tag": "instrumentation:name",
       "value": [
        "opentelemetry.instrumentation.fastapi"
       ],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "user_auth" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "",
       "valueType": "duration"
      },
      {
       "id": "status",
       "isCustomValue": false,
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{instrumentation:name=\"opentelemetry.instrumentation.fastapi\" && resource.service.name=\"user_auth_api\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}