{
 "title": "System",
 "description": "Focuses on infrastructure usage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "System", "label": "System", "query": "host.docker.internal:9092" }
  ]
 },
 "panels": [
  { "title": "Observation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys:instance:cpu_load:percent:5m{instance=\"${System}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Currently displayed value is a stub:\nUse the query below\nnode_hwmon_temp_celsius{chip=\"coretemp\", sensor=~\"Package id 0\", instance=\"${System}\"}\n",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-((avg_over_time(node_memory_MemAvailable_bytes{instance=\"${System}\"}[5m]) / node_memory_MemTotal_bytes{instance=\"${System}\"}) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys:instance:net_in:mbs:5m{instance=\"${System}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds{instance=\"${System}\"} - node_boot_time_seconds{instance=\"${System}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free disk space left",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sys:instance_mountpoint:storage_free:mb{instance=\"${System}\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "sys:instance_mountpoint:storage_total:mb{instance=\"${System}\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys:instance:ram_load:percent:5m{instance=\"${System}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys:instance:disk_load:percent:5m{instance=\"${System}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sys:instance:net_out:mbs:5m{instance=\"${System}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CPU Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Utilization [5m]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys:instance_cpu:cpu_load:percent:5m",
     "legendFormat": "Core {{cpu }}"
    }
   ]
  },
  {
   "title": "CPU Temps (Cores) [5m]",
   "type": "timeseries",
   "description": "Currently displayed value is a stub. \nUse the following query:\nnode_hwmon_temp_celsius{chip=\"coretemp\", sensor=~\"Core.*\", instance=\"${System}\"}\n",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance, cpu) (rate(node_cpu_seconds_total{instance=\"${System}\", mode=\"idle\"}[5m])) * 100) + 35",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  { "title": "RAM Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "AVG RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"${System}\"} - node_memory_MemAvailable_bytes{instance=\"${System}\"}) / 10^6",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"${System}\"} / 10^6",
     "legendFormat": "RAM Total"
    }
   ]
  },
  {
   "title": "RAM: Major page faults/min [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault{instance=\"${System}\"}[5m])\r\n",
     "legendFormat": "RAM Used"
    }
   ]
  },
  { "title": "Disk details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Disk IO weighted time rate [5m]",
   "type": "timeseries",
   "description": "Shows how much time is spent per operation on average.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{instance=\"${System}\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IO weighted time rate [5m]",
   "type": "timeseries",
   "description": "Shows how much time is spent per operation on average.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sys:instance:disk_read:kb:5m{instance=\"${System}\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "sys:instance:disk_written:kb:5m{instance=\"${System}\"}",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Network details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "AVG Net Usage [5m]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sys:instance:net_in:mbs:5m{instance=\"${System}\"}",
     "legendFormat": "In"
    },
    {
     "expr": "sys:instance:net_out:mbs:5m{instance=\"${System}\"}",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Packet loss R/T [5m]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sys:instance:net_loss_in:pps:5m{instance=\"${System}\"}",
     "legendFormat": "Recieve drops"
    },
    {
     "expr": "sys:instance:net_loss_out:pps:5m{instance=\"${System}\"}",
     "legendFormat": "Transmit drops"
    }
   ]
  },
  {
   "title": "Errors/sec R/T [5m]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "errors/sec" } },
   "targets": [
    {
     "expr": "sys:instance:net_err_in:eps:5m{instance=\"${System}\"}",
     "legendFormat": "Recieve errors"
    },
    {
     "expr": "sys:instance:net_err_out:eps:5m{instance=\"${System}\"}",
     "legendFormat": "Transmit errors"
    }
   ]
  }
 ]
}