from app.common.exceptions import AppBaseException


class AuthBaseException(AppBaseException):
    """Base for auth exceptions"""

class CredentialsException(AuthBaseException): ...
class InvalidTokenError(AuthBaseException): ...
class TokenExpiredException(AuthBaseException): ... 
class LoggedOutException(AuthBaseException): ... 